version: '3.1'
services:
  api:
    image: triplee1/estatetrustv1
    depends_on:
      - postgres
    ports:
      - 80:8000
    command: uvicorn api.v1.main:app --port 80
    env:
      OAUTH2_SECRET_KEY: ${{ secrets.OAUTH2_SECRET_KEY }}
      DB_USER_PASSW: ${{ secrets.DB_USER_PASSW }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ACCESS_TOKEN_EXPIRE_WEEKS: ${{ secrets.ACCESS_TOKEN_EXPIRE_WEEKS }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  postgres:
    image: postgres
    env:
      - POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB: ${{ secrets.DB_NAME }}
      - POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
