version: '3.1'
services:
  api:
    image: triplee1/estatetrustv1
    depends_on:
      - postgres
    ports:
      - 80:8000
    command: uvicorn api.v1.main:app --port 80
    env_file:
      - ./.env
  postgres:
    image: postgres
    env:
      - POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB: ${{ secrets.DB_NAME }}
      - POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
