version: '3'
services:
  api:
    image: triplee1/estatetrustv1
    depends_on:
      - postgres
    ports:
      - 80:8000
    command: uvicorn api.v1.main:app --port 80
    env_file:
      - ./.env
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
