version: '3.1'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:./:ro
    command: uvicorn api.v1.main:app --reload
    env_file:
      - ./.env
  postgres:
    image: postgres
    env:
      - POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB: ${{ secrets.DB_NAME }}
      - POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    env_file:
      ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
